services:
  node-rest:
    build:
      context: ./node-rest
      dockerfile: Dockerfile
    env_file:
      - ./node-rest/.env.production
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"     # HTTP redirect to HTTPS
      - "443:443"   # HTTPS served content
    depends_on:
      - node-rest
    restart: unless-stopped
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Mount SSL certs
    networks:
      - backend

networks:
  backend:
    driver: bridge


# version: '3.8'

# services:
#   nginx:
#     build:
#       context: ./nginx
#     ports:
#       - "80:80"
#     depends_on:
#       - node-rest
#     networks:
#       - backend
#   rest:
#     build:
#       context: ./node-rest
#     ports:
#       - "3000:3000"
#     depends_on:
#       - python-grpc
#     networks:
#       - backend

#   python-grpc:
#     build:
#       context: ./python-grpc
#     ports:
#       - "50051:50051"
#     networks:
#       - backend

# networks:
#   backend:
